// Generated by CoffeeScript 1.3.3
(function() {
  var animating, bindEvents, currentActive, foldInactive, init, menuElm, toggleMenu;

  menuElm = null;

  currentActive = null;

  animating = false;

  init = function() {
    menuElm = $('.secondary-menu');
    if (!menuElm.length) {
      return;
    }
    bindEvents();
    return foldInactive();
  };

  bindEvents = function() {
    return menuElm.on('click', 'a', toggleMenu);
  };

  foldInactive = function() {
    var toFold;
    toFold = menuElm.find('> ul > li:not(.active)');
    toFold.find('ul').slideUp(0);
    currentActive = menuElm.find('.active');
  };

  toggleMenu = function(e) {
    var tgt, toFold, ulElms;
    tgt = $(e.target);
    ulElms = tgt.parentsUntil('.secondary-menu', 'ul');
    if (ulElms.length !== 1) {
      return;
    }
    toFold = tgt.siblings('ul');
    if (!toFold.length) {
      return;
    }
    e.preventDefault();
    if (animating) {
      return;
    }
    animating = true;
    if (toFold.closest('li').hasClass('active')) {
      return toFold.slideToggle(500, function() {
        return animating = false;
      });
    } else {
      toFold.slideDown(500);
      return currentActive.find('ul').slideUp(500, function() {
        currentActive.removeClass('active');
        currentActive = toFold.closest('li');
        currentActive.addClass('active');
        return animating = false;
      });
    }
  };

  $(init);

}).call(this);
